service: dashapp-3
runtime: python
env: flex

runtime_config:
    python_version: 3

resources:
    cpu: 1
    memory_gb: 6
    disk_size_gb: 10
                             
entrypoint: gunicorn -b 0.0.0.0:8080 main:server

env_variables:
  PKL_BUCKET:  'project-id.appspot.com'